export const ADD_DETAIL = "ADD_DETAIL";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_INLINE_PRODUCT = "ADD_INLINE_PRODUCT";
export const CLEAR_INLINE_PRODUCT = "CLEAR_INLINE_PRODUCT";
export const CHECK_INLINE_PRODUCT = "CHECK_INLINE_PRODUCT";
// supplier action
export const SUBMIT_SUPPLIER_DATA = "SUBMIT_SUPPLIER_DATA";
export const CLOSE_SNACKBAR = "CLOSE_SNACKBAR";
export const GET_SUPPLIER = "GET_SUPPLIER";
export const FORM_SUBMITTED = "FORM_SUBMITTED";
export const SET_VALUE = "SET_VALUE";
